# Generated by Django 4.2.7 on 2023-12-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorrequest',
            name='mentor',
        ),
    ]
