# Generated by Django 4.2.7 on 2023-11-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_baseuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
