# Generated by Django 4.2.1 on 2023-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_entrepreneurprofile_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
