# Generated by Django 4.2.1 on 2023-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_entrepreneurprofile_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
