# Generated by Django 4.2.7 on 2023-12-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_baseuser_role_mentorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
