# Generated by Django 4.2.7 on 2023-12-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mentorprofile_joined_at_mentorprofile_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepreneurs', to='accounts.mentorprofile'),
        ),
    ]
