# Generated by Django 4.2.7 on 2023-11-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_baseuser_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=50)),
                ('brief_about', models.TextField()),
                ('startup_industry', models.CharField(max_length=50)),
                ('startup_stage', models.CharField(max_length=50)),
                ('presentation_video', models.FileField(upload_to='startup_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entrepreneurs', models.ManyToManyField(related_name='startups', to='accounts.entrepreneurprofile')),
            ],
        ),
    ]
