# Generated by Django 4.2.7 on 2023-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupdetail',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='startupdetail',
            name='startup_industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Healthcare'), ('finance', 'Finance'), ('edu', 'Education'), ('retail', 'Retail'), ('entertainment', 'Entertainment'), ('food', 'Food and Beverage'), ('travel', 'Travel and Hospitality'), ('manufacturing', 'Manufacturing'), ('fashion', 'Fashion'), ('media', 'Media and Communication'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='startupdetail',
            name='startup_stage',
            field=models.CharField(choices=[('pre_seed', 'Pre-Seed Stage'), ('seed', 'Seed Stage'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('expansion', 'Expansion Phase'), ('exit', 'Exit Phase')], max_length=50),
        ),
    ]
