# Generated by Django 4.2.7 on 2023-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_creation', '0002_startupdetail_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupdetail',
            name='startup_level',
            field=models.CharField(blank=True, choices=[('biginner', 'Biginner'), ('intermediate', 'Intermediate'), ('completed', 'completed'), ('pitch', 'Ready to Pitch')], max_length=50, null=True),
        ),
    ]
